### PR TITLE
Do not support --net option.

### PR DESCRIPTION
**Pull request by rtnpro**
Drop support for `--net` option in opencompose as it's more of an infrastructure/operation specification than an application specification. All the developers should be bothered with is to identify the services they depend on, and the orchestration engine should take care running the application in the proper scope (namespace, network, etc.) so that the application can access the services it depends on.

### CODE REVIEW

**Comment by rtnpro** [comment]
@kadel @pradeepto @pmuir Please share your thoughts.

**Comment by l0rd** [comment]
Maybe I'm missing something but if opencompose doesn't support the `--net` option it won't be possible start some applications. Tipically `--net` is used when different containers need to share the same network stack (i.e. https://eclipse-che.readme.io/docs/usage-docker needs that).

**Comment by kadel** [comment]
We will need some form of network definition. Question maybe should be where is right place to define that.  Orchestrations platforms differs a lot in how they do networking. 
If we are considering that OpenCompose will have two parts like it is mentioned in [proposal on slide 5](https://docs.google.com/presentation/d/1TLSRQ5aWfmaCqZ9FS0uE-IOVQoP_DX6ioo0jqWIrmwk/edit#slide=id.g12cdb8e5f7_0_5), than I would put networking into vendor specific part.

**Comment by pradeepto** [comment]
@rtnpro I will close this PR. We discussed this yesterday during the meeting as well. Not supporting networking option doesn't look like a good idea at all.

**Pull request closed without merging**
